services:
  - type: web
    name: my-python-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api.index:app --host 0.0.0.0 --port 8000"